# Generated by Django 6.0 on 2026-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_freelancerpaymentsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpaymentsettings',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
