# Generated by Django 6.0 on 2026-01-29 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_categories__name_e3ad98_idx_and_more'),
        ('profiles', '0004_alter_freelancerpaymentsettings_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['total_spent'], name='profiles_cl_total_s_813901_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerpackage',
            index=models.Index(fields=['package_type'], name='profiles_fr_package_e8ec49_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerpackage',
            index=models.Index(fields=['price'], name='profiles_fr_price_6e617e_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerportfolio',
            index=models.Index(fields=['created_at'], name='profiles_fr_created_d54533_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['availability'], name='profiles_fr_availab_7d0759_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['experience_level'], name='profiles_fr_experie_bdca7b_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['total_earnings'], name='profiles_fr_total_e_bccce6_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['created_at'], name='profiles_fr_created_f4564f_idx'),
        ),
    ]
