# Generated by Django 6.0 on 2026-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_clientprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
