# Generated by Django 6.0 on 2026-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_freelancerprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
            ],
        ),
    ]
