# Generated by Django 6.0 on 2026-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_freelancertodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancertodo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
