# Generated by Django 6.0 on 2026-01-31 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('proposal_accepted', 'Proposal Accepted'), ('invitation_received', 'New Invitation'), ('offer_received', 'New Offer'), ('contract_started', 'Contract Started'), ('delivered', 'Work Delivered'), ('revision_requested', 'Revision Requested'), ('revision_accepted', 'Revision Accepted'), ('revision_rejected', 'Revision Rejected'), ('contract_completed', 'Contract Completed'), ('payment_credited', 'Payment Credited')], max_length=50)),
                ('message', models.TextField()),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='communicati_recipie_e3882c_idx')],
            },
        ),
    ]
