# Generated by Django 6.0 on 2026-02-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='freelancer', max_length=15),
        ),
    ]
