# Generated by Django 6.0 on 2026-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(default='freelancer', max_length=20),
        ),
    ]
