# Generated by Django 6.0 on 2026-02-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_message_sender_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('proposal_accepted', 'Proposal Accepted'), ('invitation_received', 'New Invitation'), ('offer_received', 'New Offer'), ('contract_started', 'Contract Started'), ('delivered', 'Work Delivered'), ('revision_requested', 'Revision Requested'), ('revision_accepted', 'Revision Accepted'), ('revision_rejected', 'Revision Rejected'), ('contract_completed', 'Contract Completed'), ('payment_credited', 'Payment Credited'), ('new_message', 'New Message Received')], max_length=50),
        ),
    ]
