# Generated by Django 6.0 on 2025-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.AddField(
            model_name='project',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('range', 'Range Price')], default='fixed', max_length=10),
        ),
    ]
