# Generated by Django 6.0 on 2025-12-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0002_remove_project_budget_project_fixed_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_skills', to='categories.skill'),
        ),
        migrations.AddConstraint(
            model_name='projectskill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_name__isnull', True), ('skill__isnull', False)), models.Q(('custom_name__isnull', False), ('skill__isnull', True)), _connector='OR'), name='projectskill_requires_skill_or_custom_name'),
        ),
    ]
