# Generated by Django 6.0 on 2026-01-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_freelancerpaymentsettings_and_more'),
        ('projects', '0003_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='profiles.freelancerprofile'),
        ),
    ]
