# Generated by Django 6.0 on 2026-01-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_freelancerpaymentsettings_and_more'),
        ('projects', '0004_alter_invitation_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='profiles.freelancerpackage'),
        ),
    ]
