# Generated by Django 6.0 on 2026-01-29 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('profiles', '0004_alter_freelancerpaymentsettings_is_verified'),
        ('projects', '0005_alter_invitation_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status'], name='projects_in_status_1dd0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['created_at'], name='projects_in_created_a53d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='projects_pr_status_80c097_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['created_at'], name='projects_pr_created_b569c4_idx'),
        ),
    ]
