# Generated by Django 6.0 on 2026-02-07 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_clientprofile_profiles_cl_total_s_813901_idx_and_more'),
        ('projects', '0006_invitation_projects_in_status_1dd0f9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.freelancerpackage'),
        ),
    ]
