# Generated by Django 6.0 on 2026-02-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_clientprofile_profiles_cl_total_s_813901_idx_and_more'),
        ('projects', '0007_alter_proposal_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='profiles.freelancerpackage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.freelancerpackage'),
            preserve_default=False,
        ),
    ]
