# Generated by Django 6.0 on 2026-02-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='paypal_email',
            field=models.EmailField(default='grolance@business.com', help_text='The master PayPal account email used for processing platform payouts.', max_length=254),
        ),
    ]
