# Generated by Django 6.0 on 2026-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'CMS Section',
                'verbose_name_plural': 'CMS Sections',
            },
        ),
    ]
