# Generated by Django 6.0 on 2026-01-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractrevision_rejection_message_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_business_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_platform_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('completed_projects_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total_amount',
            new_name='amount_total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_details', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('escrow', 'Held in Escrow'), ('released', 'Released to Freelancer'), ('refunded', 'Refunded to Client')], default='pending', max_length=20),
        ),
    ]
