# Generated by Django 6.0 on 2026-01-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_platformanalytics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='paypal_capture_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='paypal_order_id',
        ),
    ]
