# Generated by Django 6.0 on 2026-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_contracts_c_status_aa7a80_idx_and_more'),
        ('payments', '0003_rename_razorpay_payment_id_payment_paypal_capture_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
    ]
