# Generated by Django 6.0 on 2026-01-17 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_funded', models.BooleanField(default=False)),
                ('paid_to_freelancer', models.BooleanField(default=False)),
                ('client_signature', models.TextField()),
                ('client_signature_type', models.CharField(choices=[('draw', 'Draw'), ('type', 'Type')], max_length=10)),
                ('freelancer_signature', models.TextField(blank=True, null=True)),
                ('freelancer_signature_type', models.CharField(choices=[('draw', 'Draw'), ('type', 'Type')], max_length=10, null=True)),
                ('client_signed_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('freelancer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('freelancer_ip', models.GenericIPAddressField(null=True)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('active', 'Active'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'In Dispute')], default='offered', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_freelancer', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='projects.project')),
            ],
        ),
    ]
