# Generated by Django 6.0 on 2026-01-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('profiles', '0002_freelancerbankdetails_freelancerpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='profiles.freelancerpackage'),
        ),
    ]
