# Generated by Django 6.0 on 2026-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrevision',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrevision',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
