# Generated by Django 6.0 on 2026-01-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractrevision_rejection_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
