# Generated by Django 6.0 on 2026-01-27 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='legal_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='legal_document'),
        ),
    ]
