# Generated by Django 6.0 on 2026-01-29 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_legal_document'),
        ('profiles', '0005_clientprofile_profiles_cl_total_s_813901_idx_and_more'),
        ('projects', '0006_invitation_projects_in_status_1dd0f9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client_signed_at'], name='contracts_c_client__6dc243_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdeliverable',
            index=models.Index(fields=['created_at'], name='contracts_c_created_f89c74_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrevision',
            index=models.Index(fields=['status'], name='contracts_c_status_112d77_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrevision',
            index=models.Index(fields=['created_at'], name='contracts_c_created_ab87b6_idx'),
        ),
    ]
