# Generated by Django 6.0 on 2026-02-06 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_contracts_c_status_aa7a80_idx_and_more'),
        ('profiles', '0005_clientprofile_profiles_cl_total_s_813901_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scope_creep', 'Client requesting extra work outside scope'), ('no_feedback', 'Client is unresponsive'), ('Unlimited Revisions', 'contract does not limit the number of revisions included in the price, leading to endless edits.'), ('poor_quality', 'Work quality does not match proposal'), ('missed_deadline', 'Freelancer missed final deadline'), ('incomplete_work', 'Freelancer submitted unfinished work'), ('communication_issue', 'Communication breakdown'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contracts.contract')),
                ('opened_by_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.clientprofile')),
                ('opened_by_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.freelancerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='contracts.dispute')),
            ],
        ),
    ]
