# Generated by Django 6.0 on 2026-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_dispute_disputefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('offered', 'Offered'), ('active', 'Active'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'In Dispute'), ('refunded', 'Refunded')], default='offered', max_length=20),
        ),
    ]
